title: LGPD
remote_theme: just-the-docs/just-the-docs
just_the_docs:
  font_size: "120%"
aux_links:
  Código-fonte no GitHub: https://github.com/maariaceciliaholler/ecs.github.io
footer_content: "© 2025 • Manual LGPD – Bases Legais e Consentimento"
